version: '3'

services:
  ansiblecontroller:
    image: jimidesoto/ansible-controller:1.0
    container_name: controller
    networks:
      ansible-static:
        ipv4_address: 172.20.128.2
    volumes:
      - type: bind
        source: ./share
        target: /share

  target1:
    image: jimidesoto/ubuntu-disco-ssh:1.4
    container_name: target1
    networks:
      ansible-static:
        ipv4_address: 172.20.128.3
  
  target2:
    image: jimidesoto/ubuntu-disco-ssh:1.4
    container_name: target2
    networks: 
      ansible-static:
        ipv4_address: 172.20.128.4

networks:
  ansible-static:
    ipam:
      config:
        - subnet: 172.20.0.0/16
