-
    name: 'Shutdown infrastructure'
    become:
    become_method: sudo
    hosts: all
    tasks:
      - name: 'Execute a shutdown command'
        command: /usr/sbin/shutdown -h now
        sudo: yes
#end