-
    name: 'Shutdown infrastructure'
    hosts: all
    tasks:
      - name: 'Execute a shutdown command'
        command: /usr/sbin/shutdown -h now
        async: 0
        poll: 0
        ignore_errors: true
        become: yes
        
#end