-
    name: 'Shutdown infrastructure'
    become:
    become_method: sudo
    hosts: all
    tasks:
        -
            name: 'Execute a shutdown command'
            command: poweroff
            ignore_errors: yes
#end